language: java
jdk:
- oraclejdk8

sudo: true

install: true

before_script:
- sudo service postgresql stop

after_success:
- bash <(curl -s https://codecov.io/bash)
- docker-compose down

cache:
  directories:
  - $HOME/.m2

notifications:
  email: false